"""Safe SQL-to-Airflow DAG generation for MCP change sets."""
import re

import sqlglot
from sqlglot import expressions as exp

from app.services.runtime_lineage_service import parse_runtime_sql


_IDENTIFIER = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
_CRON_PART = re.compile(r"^[A-Za-z0-9*/?,\-]+$")
_CRON_PRESETS = {"@once", "@hourly", "@daily", "@weekly", "@monthly", "@yearly"}


def validate_schedule(value: str | None) -> str | None:
    schedule = (value or "").strip()
    if not schedule:
        return None
    if schedule in _CRON_PRESETS:
        return schedule
    parts = schedule.split()
    if len(parts) != 5 or any(not _CRON_PART.fullmatch(part) for part in parts):
        raise ValueError("schedule必须是5段Cron表达式或Airflow预设值")
    return schedule


def validate_transformation_sql(sql: str, default_database: str | None = None) -> dict:
    if not sql or not sql.strip():
        raise ValueError("调度SQL不能为空")
    try:
        statements = [item for item in sqlglot.parse(sql, read="mysql") if item is not None]
    except Exception as exc:
        raise ValueError(f"SQL语法解析失败: {exc}") from exc
    if len(statements) != 1 or not isinstance(statements[0], exp.Insert):
        raise ValueError("调度SQL目前只允许单条INSERT INTO ... SELECT语句")
    if not re.match(r"^\s*INSERT\s+INTO\b", sql, re.IGNORECASE):
        raise ValueError("禁止INSERT OVERWRITE等覆盖式写入，只允许INSERT INTO")
    inputs, outputs = parse_runtime_sql(sql, default_database)
    if not inputs:
        raise ValueError("INSERT语句必须包含来源表")
    if len(outputs) != 1:
        raise ValueError("INSERT语句必须且只能包含一个目标表")
    return {
        "sql": sql.strip().rstrip(";").strip(),
        "input_tables": [_qualified_name(item) for item in inputs],
        "output_tables": [_qualified_name(item) for item in outputs],
    }


def validate_dag_payload(payload: dict) -> dict:
    dag_id = str(payload.get("dag_id") or "").strip()
    task_id = str(payload.get("task_id") or "execute_sql").strip()
    if not _IDENTIFIER.fullmatch(dag_id):
        raise ValueError("dag_id不能为空且仅支持字母、数字、下划线和短横线")
    if not _IDENTIFIER.fullmatch(task_id):
        raise ValueError("task_id不能为空且仅支持字母、数字、下划线和短横线")
    schedule = validate_schedule(payload.get("schedule"))
    parsed = validate_transformation_sql(payload.get("sql") or "", payload.get("database"))
    return {**parsed, "dag_id": dag_id, "task_id": task_id, "schedule": schedule}


def render_airflow_dag(payload: dict) -> str:
    validated = validate_dag_payload(payload)
    dag_id = validated["dag_id"]
    task_id = validated["task_id"]
    schedule = validated["schedule"]
    sql = validated["sql"]
    inputs = validated["input_tables"]
    outputs = validated["output_tables"]
    datasource_name = str(payload.get("datasource_name") or "")
    database = str(payload.get("database") or "")
    return f'''"""Generated by DataMind MCP. Review in the MCP change-set center before use."""
import os
from datetime import datetime, timezone

import pymysql
import requests
from airflow.sdk import dag, get_current_context, task

SQL = {sql!r}
INPUT_TABLES = {inputs!r}
OUTPUT_TABLES = {outputs!r}


def report_lineage(state, started_at, error_message=None, affected_rows=None):
    context = get_current_context()
    lineage_token = os.environ.get("LINEAGE_EVENT_TOKEN") or os.environ["EXECUTOR_TOKEN"]
    requests.post(
        os.environ["DATAMIND_API_URL"].rstrip("/") + "/api/v1/internal/lineage/events",
        headers={{"X-Lineage-Token": lineage_token}},
        json={{
            "dag_id": context["dag"].dag_id,
            "dag_run_id": context["run_id"],
            "task_id": context["task"].task_id,
            "try_number": context["ti"].try_number,
            "state": state,
            "operator_type": "DataMindMcpSqlTask",
            "sql": SQL,
            "datasource_name": {datasource_name!r},
            "default_database": {database!r},
            "input_tables": INPUT_TABLES,
            "output_tables": OUTPUT_TABLES,
            "affected_rows": affected_rows,
            "error_message": error_message,
            "start_date": started_at.isoformat(),
            "end_date": datetime.now(timezone.utc).isoformat(),
        }},
        timeout=15,
    ).raise_for_status()


@dag(
    dag_id={dag_id!r}, schedule={schedule!r}, start_date=datetime(2025, 1, 1),
    catchup=False, is_paused_upon_creation=True, tags=["datamind", "mcp"],
)
def datamind_generated_dag():
    @task(task_id={task_id!r})
    def execute_sql():
        started_at = datetime.now(timezone.utc)
        connection = pymysql.connect(
            host=os.environ["CUBEJS_DB_HOST"], port=int(os.environ.get("CUBEJS_DB_PORT", "9030")),
            user=os.environ["CUBEJS_DB_USER"], password=os.environ.get("CUBEJS_DB_PASS", ""),
            database={database!r} or os.environ.get("CUBEJS_DB_NAME", ""),
            charset="utf8mb4", autocommit=False, connect_timeout=15, read_timeout=3600,
        )
        try:
            with connection.cursor() as cursor:
                cursor.execute(SQL)
                affected_rows = max(int(cursor.rowcount or 0), 0)
            connection.commit()
            print("Executing statement:", SQL)
            print(OUTPUT_TABLES[0] + ": transformed_rows", affected_rows)
            try:
                report_lineage("success", started_at, affected_rows=affected_rows)
            except Exception as lineage_error:
                print("Runtime lineage callback failed:", lineage_error)
            return affected_rows
        except Exception as exc:
            connection.rollback()
            try:
                report_lineage("failed", started_at, error_message=str(exc))
            except Exception as lineage_error:
                print("Runtime lineage callback failed:", lineage_error)
            raise
        finally:
            connection.close()

    execute_sql()


datamind_generated_dag()
'''


def _qualified_name(ref: dict) -> str:
    return ".".join(str(value) for value in (ref.get("database"), ref.get("name")) if value)
