"""initial_schema

Revision ID: a13aae84b769
Revises: 
Create Date: 2026-08-06 15:28:30.566617+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a13aae84b769'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('component_configs', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='非敏感配置JSON,如Doris的mysql_host/mysql_port/http_port',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('component_configs', 'credentials_encrypted',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet加密的敏感凭据JSON',
               existing_nullable=True)
    op.drop_constraint(op.f('component_configs_component_code_key'), 'component_configs', type_='unique')
    op.drop_index(op.f('idx_component_configs_status'), table_name='component_configs')
    op.drop_index(op.f('idx_component_configs_type'), table_name='component_configs')
    op.create_index(op.f('ix_component_configs_component_type'), 'component_configs', ['component_type'], unique=False)
    op.create_index(op.f('ix_component_configs_status'), 'component_configs', ['status'], unique=False)
    op.create_unique_constraint(op.f('uq_component_configs_component_code'), 'component_configs', ['component_code'])
    op.drop_table_comment(
        'component_configs',
        existing_comment='外部组件连接配置(Airflow/Doris/Cube/OpenMetadata)',
        schema=None
    )
    op.drop_index(op.f('idx_data_model_fields_model'), table_name='data_model_fields')
    op.create_index(op.f('ix_data_model_fields_model_id'), 'data_model_fields', ['model_id'], unique=False)
    op.drop_table_comment(
        'data_model_fields',
        existing_comment='数据模型字段定义',
        schema=None
    )
    op.drop_constraint(op.f('data_model_versions_model_id_version_key'), 'data_model_versions', type_='unique')
    op.drop_index(op.f('idx_data_model_versions_model'), table_name='data_model_versions')
    op.create_index(op.f('ix_data_model_versions_model_id'), 'data_model_versions', ['model_id'], unique=False)
    op.create_unique_constraint(op.f('uq_data_model_versions_model_id'), 'data_model_versions', ['model_id', 'version'])
    op.drop_table_comment(
        'data_model_versions',
        existing_comment='数据模型版本历史',
        schema=None
    )
    op.drop_constraint(op.f('data_models_model_code_key'), 'data_models', type_='unique')
    op.drop_index(op.f('idx_data_models_layer'), table_name='data_models')
    op.drop_index(op.f('idx_data_models_status'), table_name='data_models')
    op.create_index(op.f('ix_data_models_layer'), 'data_models', ['layer'], unique=False)
    op.create_index(op.f('ix_data_models_status'), 'data_models', ['status'], unique=False)
    op.create_unique_constraint(op.f('uq_data_models_model_code'), 'data_models', ['model_code'])
    op.drop_table_comment(
        'data_models',
        existing_comment='数据模型管理(ODS/DWD/DWS/ADS)',
        schema=None
    )
    op.drop_index(op.f('idx_data_sources_status'), table_name='data_sources')
    op.drop_index(op.f('idx_data_sources_type'), table_name='data_sources')
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_data_sources_status'), 'data_sources', ['status'], unique=False)
    op.drop_table_comment(
        'data_sources',
        existing_comment='外部数据源配置(用于DataX同步的源端)',
        schema=None
    )
    op.drop_index(op.f('idx_datax_field_mappings_task'), table_name='datax_field_mappings')
    op.create_index(op.f('ix_datax_field_mappings_task_id'), 'datax_field_mappings', ['task_id'], unique=False)
    op.drop_table_comment(
        'datax_field_mappings',
        existing_comment='DataX同步字段映射',
        schema=None
    )
    op.alter_column('datax_tasks', 'job_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='由datax_config_gen生成的完整DataX job JSON',
               existing_nullable=False)
    op.drop_constraint(op.f('datax_tasks_task_code_key'), 'datax_tasks', type_='unique')
    op.drop_index(op.f('idx_datax_tasks_dag'), table_name='datax_tasks')
    op.drop_index(op.f('idx_datax_tasks_source'), table_name='datax_tasks')
    op.drop_index(op.f('idx_datax_tasks_status'), table_name='datax_tasks')
    op.create_index(op.f('ix_datax_tasks_dag_id'), 'datax_tasks', ['dag_id'], unique=False)
    op.create_index(op.f('ix_datax_tasks_source_datasource_id'), 'datax_tasks', ['source_datasource_id'], unique=False)
    op.create_index(op.f('ix_datax_tasks_status'), 'datax_tasks', ['status'], unique=False)
    op.create_unique_constraint(op.f('uq_datax_tasks_task_code'), 'datax_tasks', ['task_code'])
    op.drop_table_comment(
        'datax_tasks',
        existing_comment='DataX数据同步任务定义',
        schema=None
    )
    op.drop_index(op.f('idx_menus_parent'), table_name='menus')
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.drop_index(op.f('idx_operation_logs_created'), table_name='operation_logs')
    op.drop_index(op.f('idx_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('idx_operation_logs_user'), table_name='operation_logs')
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.drop_table_comment(
        'operation_logs',
        existing_comment='用户操作审计日志',
        schema=None
    )
    op.drop_constraint(op.f('permissions_permission_code_key'), 'permissions', type_='unique')
    op.create_unique_constraint(op.f('uq_permissions_permission_code'), 'permissions', ['permission_code'])
    op.drop_index(op.f('idx_publish_records_task'), table_name='publish_records')
    op.create_index(op.f('ix_publish_records_publish_task_id'), 'publish_records', ['publish_task_id'], unique=False)
    op.drop_table_comment(
        'publish_records',
        existing_comment='发布记录',
        schema=None
    )
    op.drop_index(op.f('idx_publish_tasks_status'), table_name='publish_tasks')
    op.drop_index(op.f('idx_publish_tasks_type'), table_name='publish_tasks')
    op.create_index(op.f('ix_publish_tasks_publish_type'), 'publish_tasks', ['publish_type'], unique=False)
    op.create_index(op.f('ix_publish_tasks_status'), 'publish_tasks', ['status'], unique=False)
    op.drop_table_comment(
        'publish_tasks',
        existing_comment='发布任务管理',
        schema=None
    )
    op.drop_index(op.f('idx_query_history_executed_at'), table_name='query_history')
    op.drop_index(op.f('idx_query_history_executor'), table_name='query_history')
    op.create_index(op.f('ix_query_history_executed_at'), 'query_history', ['executed_at'], unique=False)
    op.create_index(op.f('ix_query_history_executed_by'), 'query_history', ['executed_by'], unique=False)
    op.drop_table_comment(
        'query_history',
        existing_comment='SQL查询历史',
        schema=None
    )
    op.drop_index(op.f('idx_role_permissions_permission'), table_name='role_permissions')
    op.drop_constraint(op.f('roles_role_code_key'), 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_role_code'), 'roles', ['role_code'])
    op.drop_index(op.f('idx_saved_queries_creator'), table_name='saved_queries')
    op.drop_index(op.f('idx_saved_queries_name'), table_name='saved_queries')
    op.create_index(op.f('ix_saved_queries_created_by'), 'saved_queries', ['created_by'], unique=False)
    op.create_index(op.f('ix_saved_queries_query_name'), 'saved_queries', ['query_name'], unique=False)
    op.drop_table_comment(
        'saved_queries',
        existing_comment='保存的SQL查询',
        schema=None
    )
    op.drop_index(op.f('idx_task_instances_created'), table_name='task_instances')
    op.drop_index(op.f('idx_task_instances_dag_run'), table_name='task_instances')
    op.drop_index(op.f('idx_task_instances_status'), table_name='task_instances')
    op.drop_index(op.f('idx_task_instances_task'), table_name='task_instances')
    op.create_index(op.f('ix_task_instances_created_at'), 'task_instances', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_instances_dag_id'), 'task_instances', ['dag_id'], unique=False)
    op.create_index(op.f('ix_task_instances_dag_run_id'), 'task_instances', ['dag_run_id'], unique=False)
    op.create_index(op.f('ix_task_instances_status'), 'task_instances', ['status'], unique=False)
    op.drop_table_comment(
        'task_instances',
        existing_comment='任务执行实例(映射Airflow DAG Run)',
        schema=None
    )
    op.drop_index(op.f('idx_user_roles_role'), table_name='user_roles')
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active=启用, disabled=禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_users_status'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.drop_table_comment(
        'users',
        existing_comment='平台用户表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '平台用户表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active=启用, disabled=禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('idx_user_roles_role'), 'user_roles', ['role_id'], unique=False)
    op.create_table_comment(
        'task_instances',
        '任务执行实例(映射Airflow DAG Run)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_task_instances_status'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_dag_run_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_dag_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_created_at'), table_name='task_instances')
    op.create_index(op.f('idx_task_instances_task'), 'task_instances', ['task_type', 'task_id'], unique=False)
    op.create_index(op.f('idx_task_instances_status'), 'task_instances', ['status'], unique=False)
    op.create_index(op.f('idx_task_instances_dag_run'), 'task_instances', ['dag_run_id'], unique=False)
    op.create_index(op.f('idx_task_instances_created'), 'task_instances', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table_comment(
        'saved_queries',
        '保存的SQL查询',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_saved_queries_query_name'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_created_by'), table_name='saved_queries')
    op.create_index(op.f('idx_saved_queries_name'), 'saved_queries', ['query_name'], unique=False)
    op.create_index(op.f('idx_saved_queries_creator'), 'saved_queries', ['created_by'], unique=False)
    op.drop_constraint(op.f('uq_roles_role_code'), 'roles', type_='unique')
    op.create_unique_constraint(op.f('roles_role_code_key'), 'roles', ['role_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_role_permissions_permission'), 'role_permissions', ['permission_id'], unique=False)
    op.create_table_comment(
        'query_history',
        'SQL查询历史',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_query_history_executed_by'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_executed_at'), table_name='query_history')
    op.create_index(op.f('idx_query_history_executor'), 'query_history', ['executed_by'], unique=False)
    op.create_index(op.f('idx_query_history_executed_at'), 'query_history', [sa.literal_column('executed_at DESC')], unique=False)
    op.create_table_comment(
        'publish_tasks',
        '发布任务管理',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_publish_tasks_status'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_publish_type'), table_name='publish_tasks')
    op.create_index(op.f('idx_publish_tasks_type'), 'publish_tasks', ['publish_type'], unique=False)
    op.create_index(op.f('idx_publish_tasks_status'), 'publish_tasks', ['status'], unique=False)
    op.create_table_comment(
        'publish_records',
        '发布记录',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_publish_records_publish_task_id'), table_name='publish_records')
    op.create_index(op.f('idx_publish_records_task'), 'publish_records', ['publish_task_id'], unique=False)
    op.drop_constraint(op.f('uq_permissions_permission_code'), 'permissions', type_='unique')
    op.create_unique_constraint(op.f('permissions_permission_code_key'), 'permissions', ['permission_code'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'operation_logs',
        '用户操作审计日志',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.create_index(op.f('idx_operation_logs_user'), 'operation_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index(op.f('idx_operation_logs_created'), 'operation_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.create_index(op.f('idx_menus_parent'), 'menus', ['parent_id'], unique=False)
    op.create_table_comment(
        'datax_tasks',
        'DataX数据同步任务定义',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq_datax_tasks_task_code'), 'datax_tasks', type_='unique')
    op.drop_index(op.f('ix_datax_tasks_status'), table_name='datax_tasks')
    op.drop_index(op.f('ix_datax_tasks_source_datasource_id'), table_name='datax_tasks')
    op.drop_index(op.f('ix_datax_tasks_dag_id'), table_name='datax_tasks')
    op.create_index(op.f('idx_datax_tasks_status'), 'datax_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_datax_tasks_source'), 'datax_tasks', ['source_datasource_id'], unique=False)
    op.create_index(op.f('idx_datax_tasks_dag'), 'datax_tasks', ['dag_id'], unique=False)
    op.create_unique_constraint(op.f('datax_tasks_task_code_key'), 'datax_tasks', ['task_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('datax_tasks', 'job_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='由datax_config_gen生成的完整DataX job JSON',
               existing_nullable=False)
    op.create_table_comment(
        'datax_field_mappings',
        'DataX同步字段映射',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_datax_field_mappings_task_id'), table_name='datax_field_mappings')
    op.create_index(op.f('idx_datax_field_mappings_task'), 'datax_field_mappings', ['task_id'], unique=False)
    op.create_table_comment(
        'data_sources',
        '外部数据源配置(用于DataX同步的源端)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_data_sources_status'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.create_index(op.f('idx_data_sources_type'), 'data_sources', ['source_type'], unique=False)
    op.create_index(op.f('idx_data_sources_status'), 'data_sources', ['status'], unique=False)
    op.create_table_comment(
        'data_models',
        '数据模型管理(ODS/DWD/DWS/ADS)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq_data_models_model_code'), 'data_models', type_='unique')
    op.drop_index(op.f('ix_data_models_status'), table_name='data_models')
    op.drop_index(op.f('ix_data_models_layer'), table_name='data_models')
    op.create_index(op.f('idx_data_models_status'), 'data_models', ['status'], unique=False)
    op.create_index(op.f('idx_data_models_layer'), 'data_models', ['layer'], unique=False)
    op.create_unique_constraint(op.f('data_models_model_code_key'), 'data_models', ['model_code'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'data_model_versions',
        '数据模型版本历史',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq_data_model_versions_model_id'), 'data_model_versions', type_='unique')
    op.drop_index(op.f('ix_data_model_versions_model_id'), table_name='data_model_versions')
    op.create_index(op.f('idx_data_model_versions_model'), 'data_model_versions', ['model_id'], unique=False)
    op.create_unique_constraint(op.f('data_model_versions_model_id_version_key'), 'data_model_versions', ['model_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'data_model_fields',
        '数据模型字段定义',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_data_model_fields_model_id'), table_name='data_model_fields')
    op.create_index(op.f('idx_data_model_fields_model'), 'data_model_fields', ['model_id'], unique=False)
    op.create_table_comment(
        'component_configs',
        '外部组件连接配置(Airflow/Doris/Cube/OpenMetadata)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq_component_configs_component_code'), 'component_configs', type_='unique')
    op.drop_index(op.f('ix_component_configs_status'), table_name='component_configs')
    op.drop_index(op.f('ix_component_configs_component_type'), table_name='component_configs')
    op.create_index(op.f('idx_component_configs_type'), 'component_configs', ['component_type'], unique=False)
    op.create_index(op.f('idx_component_configs_status'), 'component_configs', ['status'], unique=False)
    op.create_unique_constraint(op.f('component_configs_component_code_key'), 'component_configs', ['component_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('component_configs', 'credentials_encrypted',
               existing_type=sa.TEXT(),
               comment='Fernet加密的敏感凭据JSON',
               existing_nullable=True)
    op.alter_column('component_configs', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='非敏感配置JSON,如Doris的mysql_host/mysql_port/http_port',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
