"""current schema baseline

Revision ID: e86ab4667156
Revises: 850b0bedca37
Create Date: 2026-08-10 11:50:43.781302+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e86ab4667156'
down_revision: Union[str, None] = '850b0bedca37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("users"):
        # Older DataMind deployments created their schema from
        # database/001_init_schema.sql and may already contain business data.
        # Create only missing tables, then reconcile columns added to existing
        # model tables without dropping or rewriting user data.
        from app.core.database import Base
        import app.models  # noqa: F401  -- populate Base.metadata

        Base.metadata.create_all(bind=bind, checkfirst=True)
        if inspector.has_table("data_models"):
            columns = {item["name"] for item in sa.inspect(bind).get_columns("data_models")}
            if "etl_sql" not in columns:
                op.add_column("data_models", sa.Column("etl_sql", sa.Text(), nullable=True))
            if "business_domain" not in columns:
                op.add_column("data_models", sa.Column("business_domain", sa.String(length=50), nullable=True))
                op.create_index(op.f("ix_data_models_business_domain"), "data_models", ["business_domain"])
            if "data_domain" not in columns:
                op.add_column("data_models", sa.Column("data_domain", sa.String(length=50), nullable=True))
                op.create_index(op.f("ix_data_models_data_domain"), "data_models", ["data_domain"])
        if inspector.has_table("task_instances"):
            task_columns = {
                item["name"] for item in sa.inspect(bind).get_columns("task_instances")
            }
            if "log_content" not in task_columns:
                op.add_column("task_instances", sa.Column("log_content", sa.Text(), nullable=True))
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airflow_dag_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dag_id', sa.String(length=200), nullable=False),
    sa.Column('dag_run_id', sa.String(length=250), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('execution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airflow_dag_runs')),
    sa.UniqueConstraint('dag_id', 'dag_run_id', name=op.f('uq_airflow_dag_runs_dag_id'))
    )
    op.create_index(op.f('ix_airflow_dag_runs_dag_id'), 'airflow_dag_runs', ['dag_id'], unique=False)
    op.create_index(op.f('ix_airflow_dag_runs_state'), 'airflow_dag_runs', ['state'], unique=False)
    op.create_table('business_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_name', sa.String(length=50), nullable=False),
    sa.Column('domain_code', sa.String(length=50), nullable=False),
    sa.Column('data_domain', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_domains')),
    sa.UniqueConstraint('domain_code', name=op.f('uq_business_domains_domain_code'))
    )
    op.create_table('component_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_ok', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_configs')),
    sa.UniqueConstraint('component_code', name=op.f('uq_component_configs_component_code'))
    )
    op.create_index(op.f('ix_component_configs_component_type'), 'component_configs', ['component_type'], unique=False)
    op.create_index(op.f('ix_component_configs_status'), 'component_configs', ['status'], unique=False)
    op.create_table('dag_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dag_id', sa.String(length=200), nullable=False),
    sa.Column('dag_name', sa.String(length=100), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dag_definitions')),
    sa.UniqueConstraint('dag_id', name=op.f('uq_dag_definitions_dag_id'))
    )
    op.create_table('data_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_name', sa.String(length=50), nullable=False),
    sa.Column('domain_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_domains')),
    sa.UniqueConstraint('domain_code', name=op.f('uq_data_domains_domain_code'))
    )
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('menu_name', sa.String(length=50), nullable=False),
    sa.Column('menu_type', sa.String(length=20), nullable=False),
    sa.Column('route_path', sa.String(length=200), nullable=True),
    sa.Column('component', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], name=op.f('fk_menus_parent_id_menus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menus'))
    )
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_table('metric_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_categories')),
    sa.UniqueConstraint('category_code', name=op.f('uq_metric_categories_category_code'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('permission_code', name=op.f('uq_permissions_permission_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_code', name=op.f('uq_roles_role_code'))
    )
    op.create_table('table_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_owners'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dag_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dag_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dag_id'], ['dag_definitions.id'], name=op.f('fk_dag_nodes_dag_id_dag_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dag_nodes'))
    )
    op.create_index(op.f('ix_dag_nodes_dag_id'), 'dag_nodes', ['dag_id'], unique=False)
    op.create_table('data_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_code', sa.String(length=100), nullable=False),
    sa.Column('layer', sa.String(length=20), nullable=False),
    sa.Column('database', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('etl_sql', sa.Text(), nullable=True),
    sa.Column('business_domain', sa.String(length=50), nullable=True),
    sa.Column('data_domain', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_data_models_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_models')),
    sa.UniqueConstraint('model_code', name=op.f('uq_data_models_model_code'))
    )
    op.create_index(op.f('ix_data_models_business_domain'), 'data_models', ['business_domain'], unique=False)
    op.create_index(op.f('ix_data_models_data_domain'), 'data_models', ['data_domain'], unique=False)
    op.create_index(op.f('ix_data_models_layer'), 'data_models', ['layer'], unique=False)
    op.create_index(op.f('ix_data_models_status'), 'data_models', ['status'], unique=False)
    op.create_table('data_service_apis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_name', sa.String(length=100), nullable=False),
    sa.Column('api_path', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql_template', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('database', sa.String(length=100), nullable=False),
    sa.Column('cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('cache_ttl', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_data_service_apis_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_service_apis')),
    sa.UniqueConstraint('api_path', name=op.f('uq_data_service_apis_api_path'))
    )
    op.create_index(op.f('ix_data_service_apis_status'), 'data_service_apis', ['status'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('default_schema', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_connection_test', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_connection_ok', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_data_sources_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_data_sources_status'), 'data_sources', ['status'], unique=False)
    op.create_table('etl_scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_name', sa.String(length=100), nullable=False),
    sa.Column('script_code', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_etl_scripts_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_scripts')),
    sa.UniqueConstraint('script_code', name=op.f('uq_etl_scripts_script_code'))
    )
    op.create_index(op.f('ix_etl_scripts_language'), 'etl_scripts', ['language'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('cube_name', sa.String(length=100), nullable=True),
    sa.Column('cube_measure', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_time_dimension', sa.String(length=200), nullable=True),
    sa.Column('calculation', sa.Text(), nullable=True),
    sa.Column('business_domain', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['metric_categories.id'], name=op.f('fk_metric_definitions_category_id_metric_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definitions')),
    sa.UniqueConstraint('metric_code', name=op.f('uq_metric_definitions_metric_code'))
    )
    op.create_table('metric_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('metric_label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['metric_categories.id'], name=op.f('fk_metric_mappings_category_id_metric_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_mappings'))
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_operation_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('publish_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publish_name', sa.String(length=100), nullable=False),
    sa.Column('publish_type', sa.String(length=20), nullable=False),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_environment', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_publish_tasks_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_tasks'))
    )
    op.create_index(op.f('ix_publish_tasks_publish_type'), 'publish_tasks', ['publish_type'], unique=False)
    op.create_index(op.f('ix_publish_tasks_status'), 'publish_tasks', ['status'], unique=False)
    op.create_table('query_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('database', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('fk_query_history_executed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_history'))
    )
    op.create_index(op.f('ix_query_history_executed_at'), 'query_history', ['executed_at'], unique=False)
    op.create_index(op.f('ix_query_history_executed_by'), 'query_history', ['executed_by'], unique=False)
    op.create_table('role_menus',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name=op.f('fk_role_menus_menu_id_menus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_menus_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id', name=op.f('pk_role_menus'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('saved_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('database', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_saved_queries_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_queries'))
    )
    op.create_index(op.f('ix_saved_queries_created_by'), 'saved_queries', ['created_by'], unique=False)
    op.create_index(op.f('ix_saved_queries_query_name'), 'saved_queries', ['query_name'], unique=False)
    op.create_table('spark_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_code', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('target_database', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=200), nullable=False),
    sa.Column('spark_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('dag_id', sa.String(length=100), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_spark_tasks_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spark_tasks')),
    sa.UniqueConstraint('task_code', name=op.f('uq_spark_tasks_task_code'))
    )
    op.create_index(op.f('ix_spark_tasks_dag_id'), 'spark_tasks', ['dag_id'], unique=False)
    op.create_index(op.f('ix_spark_tasks_status'), 'spark_tasks', ['status'], unique=False)
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('config_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_configs_updated_by_users')),
    sa.PrimaryKeyConstraint('config_key', name=op.f('pk_system_configs'))
    )
    op.create_table('task_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('dag_id', sa.String(length=100), nullable=False),
    sa.Column('dag_run_id', sa.String(length=200), nullable=False),
    sa.Column('run_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_content', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rows_read', sa.BigInteger(), nullable=True),
    sa.Column('rows_written', sa.BigInteger(), nullable=True),
    sa.Column('bytes_written', sa.BigInteger(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_task_instances_triggered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_instances'))
    )
    op.create_index(op.f('ix_task_instances_created_at'), 'task_instances', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_instances_dag_id'), 'task_instances', ['dag_id'], unique=False)
    op.create_index(op.f('ix_task_instances_dag_run_id'), 'task_instances', ['dag_run_id'], unique=False)
    op.create_index(op.f('ix_task_instances_status'), 'task_instances', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('data_model_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('field_comment', sa.String(length=200), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_partition', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['data_models.id'], name=op.f('fk_data_model_fields_model_id_data_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_model_fields'))
    )
    op.create_index(op.f('ix_data_model_fields_model_id'), 'data_model_fields', ['model_id'], unique=False)
    op.create_table('data_model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('table_ddl', sa.Text(), nullable=True),
    sa.Column('field_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_log', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_data_model_versions_created_by_users')),
    sa.ForeignKeyConstraint(['model_id'], ['data_models.id'], name=op.f('fk_data_model_versions_model_id_data_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_model_versions')),
    sa.UniqueConstraint('model_id', 'version', name=op.f('uq_data_model_versions_model_id'))
    )
    op.create_index(op.f('ix_data_model_versions_model_id'), 'data_model_versions', ['model_id'], unique=False)
    op.create_table('data_service_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('api_path', sa.String(length=200), nullable=False),
    sa.Column('caller_user_id', sa.UUID(), nullable=True),
    sa.Column('caller_username', sa.String(length=50), nullable=True),
    sa.Column('request_params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['data_service_apis.id'], name=op.f('fk_data_service_call_logs_api_id_data_service_apis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caller_user_id'], ['users.id'], name=op.f('fk_data_service_call_logs_caller_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_service_call_logs'))
    )
    op.create_index(op.f('ix_data_service_call_logs_api_id'), 'data_service_call_logs', ['api_id'], unique=False)
    op.create_index(op.f('ix_data_service_call_logs_created_at'), 'data_service_call_logs', ['created_at'], unique=False)
    op.create_table('data_service_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['data_service_apis.id'], name=op.f('fk_data_service_permissions_api_id_data_service_apis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_data_service_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_service_permissions')),
    sa.UniqueConstraint('api_id', 'role_id', name=op.f('uq_data_service_permissions_api_id'))
    )
    op.create_table('datasource_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], name=op.f('fk_datasource_permissions_datasource_id_data_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_datasource_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasource_permissions')),
    sa.UniqueConstraint('datasource_id', 'role_id', name=op.f('uq_datasource_permissions_datasource_id'))
    )
    op.create_table('datax_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_code', sa.String(length=100), nullable=False),
    sa.Column('source_datasource_id', sa.UUID(), nullable=False),
    sa.Column('source_table', sa.String(length=200), nullable=False),
    sa.Column('source_schema', sa.String(length=100), nullable=True),
    sa.Column('where_clause', sa.Text(), nullable=True),
    sa.Column('split_pk', sa.String(length=100), nullable=True),
    sa.Column('target_database', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('job_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_mode', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('error_limit_record', sa.Integer(), nullable=False),
    sa.Column('error_limit_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('dag_id', sa.String(length=100), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_datax_tasks_created_by_users')),
    sa.ForeignKeyConstraint(['source_datasource_id'], ['data_sources.id'], name=op.f('fk_datax_tasks_source_datasource_id_data_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datax_tasks')),
    sa.UniqueConstraint('task_code', name=op.f('uq_datax_tasks_task_code'))
    )
    op.create_index(op.f('ix_datax_tasks_dag_id'), 'datax_tasks', ['dag_id'], unique=False)
    op.create_index(op.f('ix_datax_tasks_source_datasource_id'), 'datax_tasks', ['source_datasource_id'], unique=False)
    op.create_index(op.f('ix_datax_tasks_status'), 'datax_tasks', ['status'], unique=False)
    op.create_table('publish_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publish_task_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publish_task_id'], ['publish_tasks.id'], name=op.f('fk_publish_records_publish_task_id_publish_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_records'))
    )
    op.create_index(op.f('ix_publish_records_publish_task_id'), 'publish_records', ['publish_task_id'], unique=False)
    op.create_table('datax_field_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('source_column', sa.String(length=200), nullable=False),
    sa.Column('target_column', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['datax_tasks.id'], name=op.f('fk_datax_field_mappings_task_id_datax_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datax_field_mappings'))
    )
    op.create_index(op.f('ix_datax_field_mappings_task_id'), 'datax_field_mappings', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError(
        "The current schema baseline is intentionally irreversible; restore a database backup instead."
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datax_field_mappings_task_id'), table_name='datax_field_mappings')
    op.drop_table('datax_field_mappings')
    op.drop_index(op.f('ix_publish_records_publish_task_id'), table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_index(op.f('ix_datax_tasks_status'), table_name='datax_tasks')
    op.drop_index(op.f('ix_datax_tasks_source_datasource_id'), table_name='datax_tasks')
    op.drop_index(op.f('ix_datax_tasks_dag_id'), table_name='datax_tasks')
    op.drop_table('datax_tasks')
    op.drop_table('datasource_permissions')
    op.drop_table('data_service_permissions')
    op.drop_index(op.f('ix_data_service_call_logs_created_at'), table_name='data_service_call_logs')
    op.drop_index(op.f('ix_data_service_call_logs_api_id'), table_name='data_service_call_logs')
    op.drop_table('data_service_call_logs')
    op.drop_index(op.f('ix_data_model_versions_model_id'), table_name='data_model_versions')
    op.drop_table('data_model_versions')
    op.drop_index(op.f('ix_data_model_fields_model_id'), table_name='data_model_fields')
    op.drop_table('data_model_fields')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_task_instances_status'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_dag_run_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_dag_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_created_at'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_spark_tasks_status'), table_name='spark_tasks')
    op.drop_index(op.f('ix_spark_tasks_dag_id'), table_name='spark_tasks')
    op.drop_table('spark_tasks')
    op.drop_index(op.f('ix_saved_queries_query_name'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_created_by'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_table('role_permissions')
    op.drop_table('role_menus')
    op.drop_index(op.f('ix_query_history_executed_by'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_executed_at'), table_name='query_history')
    op.drop_table('query_history')
    op.drop_index(op.f('ix_publish_tasks_status'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_publish_type'), table_name='publish_tasks')
    op.drop_table('publish_tasks')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('metric_mappings')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_etl_scripts_language'), table_name='etl_scripts')
    op.drop_table('etl_scripts')
    op.drop_index(op.f('ix_data_sources_status'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_data_service_apis_status'), table_name='data_service_apis')
    op.drop_table('data_service_apis')
    op.drop_index(op.f('ix_data_models_status'), table_name='data_models')
    op.drop_index(op.f('ix_data_models_layer'), table_name='data_models')
    op.drop_index(op.f('ix_data_models_data_domain'), table_name='data_models')
    op.drop_index(op.f('ix_data_models_business_domain'), table_name='data_models')
    op.drop_table('data_models')
    op.drop_index(op.f('ix_dag_nodes_dag_id'), table_name='dag_nodes')
    op.drop_table('dag_nodes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_table('table_owners')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('metric_categories')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_table('data_domains')
    op.drop_table('dag_definitions')
    op.drop_index(op.f('ix_component_configs_status'), table_name='component_configs')
    op.drop_index(op.f('ix_component_configs_component_type'), table_name='component_configs')
    op.drop_table('component_configs')
    op.drop_table('business_domains')
    op.drop_index(op.f('ix_airflow_dag_runs_state'), table_name='airflow_dag_runs')
    op.drop_index(op.f('ix_airflow_dag_runs_dag_id'), table_name='airflow_dag_runs')
    op.drop_table('airflow_dag_runs')
    # ### end Alembic commands ###
